wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.10
    cli_version: 0.15.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1698674498.145895
    t:
      1:
      - 1
      - 55
      - 95
      - 105
      2:
      - 1
      - 55
      - 95
      - 105
      3:
      - 13
      - 23
      4: 3.9.10
      5: 0.15.10
      8:
      - 5
